config/routes.rb
Rails.application.routes.draw do
  get 'animals/index'
  resources :animals
  root 'animals#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_one_attached :avatar
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end
  def show
    @animal = Animal.find(params[:id])
  end
  def new
    @animal = Animal.new
  end
  def create
    @animal = Animal.new(params.require(:animal).permit(:name, :animal_type, :avatar))
    @animal.save
    /redirect_to @animals/
    redirect_to :action => "index"
  end
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    redirect_to :action => "index"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animals/index.html.erb
<div class="container">

  <h1>Список питомцев</h1>
  <div style="text-align:center">
    <%= button_tag(:type => 'button', class: 'btn-bg') do %>
    <% link_to "Добавить животное", new_animal_path %>
  <% end %>
  </div>
  <div id="gallery">
    <% @animals.each do |animal| %>
    <figure class="photo">
      <%= link_to image_tag(animal.avatar, :class => "photo-img"), animal_path(animal), class: 'photo-a' %>
      <figcaption><%= animal.name %></figcaption>
      <figcaption><%= animal.animal_type %></figcaption>
      <figcaption><%= link_to 'Destroy', animal_path(animal),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } %></figcaption>
    </figure>
    <% end %>
  </div>
</div>

app/views/animals/new.html.erb
<%= form_with scope: :animal, url: animals_path, local: true do |form| %>
  <div class="add-form">
  <h1>Додати друга</h1>
  <p>
    <%= form.label :Кличка %><br>
    <%= form.text_field :name, class: 'textbox' %>
  </p>

  <p>
    <%= form.label :Тварина %><br>
    <%= form.select :animal_type, options_for_select([%w(Dog dog), %w(Cat cat)]), {}, {class: 'textbox'} %>
  </p>

  <div>
    <%= form.label :Фото %><br>
    <%= form.file_field :avatar, class: "btn-bg"%>
  </div>
    <div style="text-align:center">
      <%= form.submit class: "btn-save" %>
    </div>

  </div>
<% end %>

app/views/animals/show.html.erb
<div>
  <strong>Кличка:</strong>
  <%= @animal.name %>
</div>

<div>
  <strong>Животное:</strong>
  <%= @animal.animal_type %>
</div>
<div>
  <strong>Photo:</strong>
  <%= image_tag(@animal.avatar) if @animal.avatar.attached? %>
</div>
<%= button_tag(:type => 'button', class: 'btn-bg') do %>
  <% link_to "Главная", animals_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>